### ISSUE TITLE
"Continuous" lint results not updating until save and modify buffer

### ISSUE THREAD

**Issue by smallgram** [CasperCL/Python-Lint.novaextension#10]
If you are running in "continuous check" mode, the linting errors are not actually reported until you save and then edit something. This is because the linters are being run on the last saved file not the current buffer. Also they are triggered only on edit in "continuous check" mode, so no update when just saved.

This makes the "continuous checking" mode no better (and also buggier) than the "lint on save" method.

I have a few half-baked ideas for this:
1) run the linters "live" (with a delay) on the current buffer (or in the case of flake8, on a diff?)
2) find a way to pipe the current buffer to the linters (with a delay)
3) run the linter as a module in a python process?

Any other ideas? I tried to look at the Sublime Python linter plug-in to see how they are doing it and at a _cursory glance_ they appear to be taking advantage of the internal Sublime interpreter...

"Run on save" is working well in the meantime and I made that the default preference.

Thanks!

**Comment by CasperCL** [comment]
Hi again! Really great to see you gave this some more thought. 

From what I understand, it's possible to get the [active text editor](https://docs.nova.app/api-reference/workspace/#activetexteditor) from the workspace, from this we can get the [document](https://docs.nova.app/api-reference/text-editor/#document). The TextDocument seems to expose some relevant state: [`isDirty`](https://docs.nova.app/api-reference/text-document/#isdirty): Returns true if the document has modifications that are not yet saved to disk. If it's dirty, get the contents of the document with `document.getTextInRange(Range(0, document.length))` and pipe it to the linter.

```javascript
let document = nova.workspace.activeTextEditor.document
console.log(`isDirty: ${document.isDirty}`)
if (document.isDirty) {
    let range = new Range(0, document.length);
    console.log(document.getTextInRange(range))
}
```

Just tested this, it does indeed hand you the buffer, which is neat.

We could save this to a temp file or directly pass it via bash to the linter.

Can you elaborate on 3? Sounds interesting.

**Comment by smallgram** [comment]
Yes, it seems like saving some kind of a temp file would work the most consistently...

3) was just an idea to use the linters' API as a Python module to directly read the AST for the module it's checking. Seems like the public API for flake8, at least, is only set up to be run on files currently... Not sure if it's doable using some of the lower-level linting libraries or if it's a fool's errand.

As far as directly piping via bash, I haven't found that flake8, for example, supports that--except on git-style diffs apparently?
