### ISSUE TITLE
Strange results from MyPy

### ISSUE THREAD

**Issue by drcongo** [CasperCL/Python-Lint.novaextension#4]
<img width="971" alt="Screen Shot 2020-09-23 10 54 26 PM" src="https://user-images.githubusercontent.com/39289/94074270-dc67f400-fdf0-11ea-8a4c-90645a679dad.png">

All my MyPy hints appear on the wrong line, and in the above example, doesn't even seem to be for the right file. `main_image` doesn't appear anywhere in the code on this file. I _think_ it's also ignoring my MyPy config in `setup.cfg` but I see you already have a ticket open for that at #1

**Comment by CasperCL** [comment]
Hi there! Thanks for reporting this issue. I noticed this issue as well yesterday. Still trying to pinpoint the exact issue.

>  I think it's also ignoring my MyPy config in setup.cfg but I see you already have a ticket open for that at #1

Yes that's definitly it. I tried to create minimal viable solution for linters and build from there. You can workaround that for the time being by supplying the config in the CLI args in preferences like this: 
> --config-file path/to/setup.cfg

**Comment by CasperCL** [comment]
I found the issue: if you feed mypy a single file it will follow the imports in that file and report issues in those files as well.
The solution is to pass `--follow-imports=silent`. See https://mypy.readthedocs.io/en/stable/running_mypy.html#following-imports.

I''ll create a fix for it later today.

**Comment by CasperCL** [comment]
Issue still persists as mentioned in #7

**Comment by CasperCL** [comment]
@drcongo @ReagentX I've released 0.2.1 Can you please confirm or deny if the issue has been resolved? I'm having trouble reproducing the issue.

If it hasn't been resolved, could you please help me fix it? All I ask is a dump of your debug log. Follow these steps:
1. Disable all linters except mypy
2. Open the debug log by clicking the middle icon in the top right corner and selecting 'Show debug pane':
![image](https://user-images.githubusercontent.com/6095436/94184503-48576480-fea4-11ea-8f52-b50c81239653.png)
3. Open the file you're experiencing issues with
4. **Clear** the debug log with the button **Clear** on the far top right of the debug log
5. Save the file to trigger mypy
6. Copy the debug and share it here please
7. Please add a screenshot of the editor showing the issue if it helps
8. Please describe what you're expecting

Thanks in advance!

**Comment by ReagentX** [comment]
I am unable to replicate the issue on 0.2.1: 

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1920666/94186421-b2581580-fe74-11ea-8084-2826137ace9a.png">

**Comment by CasperCL** [comment]
Woohoo! Happy to hear. Thanks for checking 🙂

**Comment by ReagentX** [comment]
Thank you for supporting modern Python development in Nova!

**Comment by drcongo** [comment]
Working here too! Thanks for the super fast response!
